//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesafioEntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materia()
        {
            this.profesor = new HashSet<profesor>();
        }
    
        public int id_materia { get; set; }
        [Display(Name = "Materia")]
        public string nmateria { get; set; }
        [Display(Name = "Codigo")]
        public string codigo_materia { get; set; }
        [Display(Name = "Curso")]
        public Nullable<int> curso { get; set; }
        public int id_tipo_materia { get; set; }
        public int id_titulacion { get; set; }
        [Display(Name = "Creditos Teoricos")]
        public Nullable<decimal> creditos_teoricos { get; set; }
        [Display(Name = "Creditos de Laboratorio")]
        public Nullable<decimal> creditos_laboratorio { get; set; }
        [Display(Name = "Duracion")]
        public string duracion { get; set; }
        [Display(Name = "Limite de Admision")]
        public Nullable<int> limiteAdmision { get; set; }
        [Display(Name = "Grupos de Teoria")]
        public Nullable<int> gruposTeoria { get; set; }
        [Display(Name = "Grupo de Laboratorio")]
        public Nullable<int> gruposLaboratorio { get; set; }
        
        public virtual titulacion titulacion { get; set; }
        public virtual tipoMateria tipoMateria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profesor> profesor { get; set; }
    }
}
