//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesafioEntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profesor()
        {
            this.materia = new HashSet<materia>();
        }
    
        public int id_profesor { get; set; }
        [Display(Name = "Nombres")]
        public string nombre { get; set; }
        [Display(Name = "Apellidos")]
        public string apellido { get; set; }
        [Display(Name = "Despacho")]
        public string despacho { get; set; }
        [Display(Name = "Horatio de Consultas")]
        public string horario_Consultas { get; set; }
        public int id_area_conocimiento { get; set; }
    
        public virtual areaConocimiento areaConocimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materia> materia { get; set; }
    }
}
